apiVersion: 1
policies:
  - orgId: 1
    # 默认接收器：所有未匹配到子路由的告警都发给 gpu-webhook
    receiver: gpu-webhook
    group_by:
      - alertname
      - grafana_folder
      - severity
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 12h
    routes: []
